name: Tests

on:
  push:
  pull_request:
    branches:
      - "test/setup"
      # - '*'
      # - '*/*'
      # - '**'
      # - '!master'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js, NPM & pnpm
        uses: actions/setup-node@v2
        with:
          node-version: 18.16.0
      - name: Install modules
        run: pnpm install
    # - name: Run lint
    #   run: pnpm run lint
    # - name: Run tests
    #   run: pnpm run test
